# Generated by Django 5.2 on 2026-07-02 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guestsofhotel', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestsofhotel.guest', verbose_name='Гость')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Комната')),
            ],
        ),
    ]
