# Generated by Django 5.2 on 2026-07-01 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(verbose_name='ID Комнаты')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.guest', verbose_name='Гость')),
            ],
        ),
    ]
