# Generated by Django 5.2 on 2026-07-02 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestsofhotel', '0001_initial'),
        ('history', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guestsofhotel.guest', verbose_name='Гость'),
        ),
        migrations.AlterField(
            model_name='history',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Комната'),
        ),
    ]
