# Generated by Django 5.2 on 2026-07-02 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_history_guest_alter_history_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['check_in']},
        ),
    ]
