# Generated by Django 5.2 on 2026-07-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestsofhotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['full_name']},
        ),
    ]
