# Generated by Django 5.2 on 2026-07-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('gender_id', models.IntegerField(verbose_name='ID Пола')),
                ('status_id', models.IntegerField(verbose_name='ID Статуса')),
            ],
        ),
    ]
